---
title: "Bird Watching"
subtitle: "Christian Burkhart | made with Xaringan"
author: "<br><br>Edited by Gina Reynolds, 2019"
date: "<br>"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["kunoichi", "ninjutsu"]
    nature:
      ratio: "16:9"
      highlightLines: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
knitr::opts_chunk$set(fig.height = 6, out.width = "100%", comment = " ", cache = F)
source("https://raw.githubusercontent.com/EvaMaeRey/little_flipbooks_library/master/xaringan_reveal_parenthetical.R")
```



https://github.com/r0mymendez/R/tree/master/TidyTuesday/20190621-BirdCounts
Romina Elena Mendez

---

```{r}
bird_counts <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-18/bird_counts.csv")

library(grid)
library(emojifont)
library(tidyverse)
library(ggpubr)
library(ggrepel)
```

```{r}
bird_counts %>%
  filter(how_many_counted > 0) %>%
  group_by(species)%>%
  summarise(total=sum(how_many_counted))%>%
  top_n(1,total) ->
df

df.bird=bird_counts%>%
  filter(how_many_counted>0,species %in% df$species)%>%
  group_by(year)%>%
  summarise(total=sum(how_many_counted))
```

```{r}
download.file("https://raw.githubusercontent.com/r0mymendez/R/master/TidyTuesday/20190621-BirdCounts/1.png", destfile = "temp.png")
A1 <- png::readPNG("temp.png")
A1 <- grid::rasterGrob(A1, interpolate = T) 
download.file("https://raw.githubusercontent.com/r0mymendez/R/master/TidyTuesday/20190621-BirdCounts/2.png", destfile = "temp.png")
A2 <- png::readPNG("temp.png")
A2 <- grid::rasterGrob(A2, interpolate = T) 

download.file("https://raw.githubusercontent.com/r0mymendez/R/master/TidyTuesday/20190621-BirdCounts/5c.png", destfile = "temp.png")
img_a <- png::readPNG("temp.png") 
a <- grid::rasterGrob(img_a, interpolate = T)

download.file("https://raw.githubusercontent.com/r0mymendez/R/master/TidyTuesday/20190621-BirdCounts/plot.jpg", destfile = "temp.jpg")

b <- jpeg::readJPEG("temp.jpg") 
```

```{r plotting}
ggplot(df.bird) + 
  aes(x = year, y = total) +
  geom_point(show.legend  =  F,color = '#001C3E', alpha = 0.7) +
  geom_line(show.legend  =  F,color = '#32686B') +
  annotation_custom(grob  =  a, ymin  = 30000, ymax  = 60000,
                    xmin = 1890,xmax = 2000) +
  annotation_custom(grob  =  A1, ymin  = 52000, ymax  = 72000,
                    xmin = 1920,xmax = 2000) +
  annotation_custom(grob  =  A2, ymin  = 40000, ymax  = 52000,
                    xmin = 1910,xmax = 1960) +
  annotate("text", label  = 'European Starling',
         x  =  1938, y  =  65000, size  =  15,  
         fill  = '#fffeea', 
         colour  = "black") +
  annotate("text", label  = '(1925 - 2017)',
           x  =  1940, y  =  57000, size  =  8,  
           fill  = '#fffeea',  family = "Atma Light",
           colour  = "black") +
  scale_x_continuous(breaks  =  seq(1925,2017,4)) +
  geom_label_repel(aes(label  =  total),color = 'white',
                   data  =  df.bird %>% top_n(5, total),  
                   size  =  4,  fill  = '#9DACC0',
                   alpha = 0.8,
                   family = "Atma Light" ,
                   box.padding  =  unit(0.35, "lines"),
                   point.padding  =  unit(0.3, "lines"),
                   show.legend  =  F,fontface  =  'bold',
                   hjust = 0,vjust = 0.8,
                   segment.size  = 0.8) +
  labs(caption = 'by @r0mymendez') ->
the_plot
```


`r apply_reveal("plotting")`

---

```{r thematic}
the_plot +
  theme_minimal() +
  theme(plot.caption = element_text(size = 14)) +
  theme(axis.title = element_text(size = 30)) +
  theme(plot.background = element_rect(fill = '#77939F')) +
  theme(panel.background = element_rect(fill = '#77939F')) +
  theme(axis.line = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(axis.ticks.y = element_blank()) +
  theme(panel.grid.major.x = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.grid.major.y = element_line(linetype = 2)) +
  theme(axis.text = element_text(color = 'white'))
```

---

`r apply_reveal("thematic")`


---

```{r, include = F}
ggsave(filename = "figures/bird_watch.png")
```



```{css, eval = TRUE, echo = F}
.remark-code{line-height: 1.5; font-size: 75%}
```