---
title: "Plastic Waste"
author: "Ifeoma Egbogah"
date: "5/29/2019"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(countrycode)
library(patchwork)
library("cartogram")
library(tmap)
library(tmaptools)
theme_set(theme_light())
coast_vs_waste <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/coastal-population-vs-mismanaged-plastic.csv")
mismanaged_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-mismanaged-plastic-waste-vs-gdp-per-capita.csv")
waste_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-plastic-waste-vs-gdp-per-capita.csv")
```

#Making A Cartogram
```{r}
data("World")
mismanaged2010 <- mismanaged_vs_gdp %>%
  left_join(coast_vs_waste)
mismanaged2010 <- mismanaged2010 %>%
  filter(!is.na(`Coastal population`))
write.csv(mismanaged2010, "mismanaged.csv")
  
mismanaged <- read.csv("mismanaged.csv", stringsAsFactors = TRUE)
World<- World%>%
  left_join(., mismanaged,  by= c("iso_a3" = "Code"))
pop<- cartogram_cont(World, "Coastal.population")
  
cart <- tm_shape(pop)+
  tm_polygons("Mismanaged.plastic.waste..tonnes.", n=6, style = "jenks", palette = "viridis", n=20, title= "Mismanged Plastic Waste(tonnes)")+
  tm_text("Entity", size = "Coastal.population", legend.size.show = FALSE)+
  tm_style("beaver", bg.color = "lightblue", space.color = "gray90")+
  tm_layout(main.title = "Cartogram of Coastal Population, 2010", title.size = 0.7, title ="Colour shows plastic waste that is not properly managed by a given country (2010)",frame = FALSE, legend.position = c("left", "bottom"))+
  tm_credits("Source: Our World in Data | Visualisation: Ifeoma Egbogah")
cart
#By absolute quantity China is the largest contributor of mismanaged waste but however its relative contribution (i.e kg per person per day) is not as much as Sri Lanka, Malaysia, Thailand, Egypt, Vanuatu, South Africa, Syria or Trinidad.
waste<- cartogram_cont(World, "Mismanaged.plastic.waste..tonnes.")
cart1 <- tm_shape(waste)+
  tm_polygons("Per.capita.mismanaged.plastic.waste..kilograms.per.person.per.day.", n=6, style = "jenks", palette = "viridis", n=10, title= "Plastic waste per person per day")+
  tm_text("Entity", size = "Mismanaged.plastic.waste..tonnes.", legend.size.show = FALSE)+
  tm_style("beaver", bg.color = "lightblue", space.color = "gray90")+
  tm_layout(main.title = "Cartogram of Mismanaged Plastic Waste (tonnes)", title.size = 0.6, title ="By absolute quantity, China is the largest contributor of mismanaged waste but its relative contribution (kg per person per day) is low",  frame = FALSE, legend.position = c("left", "bottom"))+
  tm_credits("Source: Our World in Data | Visualisation: Ifeoma Egbogah")
cart1
GDP<- cartogram_cont(World, "GDP.per.capita..PPP..constant.2011.international.....Rate.")
  
cart2 <- tm_shape(GDP)+
  tm_polygons("Mismanaged.plastic.waste..tonnes.", n=6, style = "jenks", palette = "viridis", n=20, title= "Mismanged Plastic Waste(tonnes)")+
  tm_text("Entity", size = "GDP.per.capita..PPP..constant.2011.international.....Rate.", legend.size.show = FALSE)+
  tm_style("beaver", bg.color = "lightblue", space.color = "gray90")+
  tm_layout(main.title = "Cartogram of GDP per capita (2010)", title.size = 0.7, title = "Countries with high GDP have low mismanaged plastic waste",  frame = FALSE, legend.position = c("left", "bottom"))+
  tm_credits("Source: Our World in Data | Visualisation: Ifeoma Egbogah")
cart2
tmap_save(cart, "cart.png", width = 16, height = 10)
tmap_save(cart1, "cart1.png", width = 16, height = 10)
tmap_save(cart2, "cart2.png", width = 16, height =10)
```