---
title: "UNGA Votes"
author: "Gina Reynolds, September 2019"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["kunoichi", "ninjutsu"]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=F}
knitr::opts_chunk$set(fig.width = 8, message = F, warning = F, 
                      comment = "", cache = F)
```

The flipbook functions are here:

```{r, echo = T}
source(file = "https://raw.githubusercontent.com/EvaMaeRey/little_flipbooks_library/master/xaringan_reveal_parentheses_balanced.R")
```


---

# Data wrangling with dplyr and tidyr

---

```{r load_packages_manipulation, echo = F, eval = T}
library(tidyverse)
library(unvotes)
un_roll_calls %>% 
  select(rcid, date) %>% 
  mutate(year = lubridate::year(date)) %>% 
  mutate(month = lubridate::month(date)) %>% 
  mutate(indicator = 1) %>% 
  group_by(year, month) %>% 
  summarise(number_of_role_calls = 
              sum(indicator, na.rm = T)) %>% 
  full_join(crossing(month = 1:12, 
                     year = 1946:2015)) %>%
  mutate(number_of_role_calls = replace_na(number_of_role_calls, 0)) %>% 
  mutate(decade = str_replace(year, "\\d$", "0")) %>% 
  mutate(decade = paste0(decade, "'s")) ->
by_month
```

`r apply_reveal("load_packages_manipulation")`

---

# Building up to a first plot...

---

```{r visualization, echo = F, eval = T}
ggplot(by_month) +
  aes(x = month) +
  aes(y = number_of_role_calls) +
  aes(col = year) +
  aes(group = year) +
  geom_line(alpha = .3) +
  scale_color_viridis_c() +
  scale_x_continuous(breaks = 1:12, 
                     expand = c(0.01,0.01),
                     label = c(" jan","feb", "march", 
                               "april", "may", "june", 
                               "july", "aug", "sept", 
                               "oct", "nov", "dec  ")) +
  scale_y_continuous(expand = c(.02, .03)) +
  labs(y = "number of votes") +
  labs(x = NULL) +
  labs(col = NULL) +
  labs(title = "Activity ramps up in the UN General Assembly ") +
  labs(subtitle = "Role call votes by month, 1946-2015") +
  labs(caption = "Data: Erik Voeten Data and Analyses of Voting in the UN General Assembly via un_votes package in R\nViz: @evamaerey w ggplot2") +
  ggdark::dark_theme_grey(base_family = "Times", 
           base_size = 13 ) +
  theme(legend.position = c(.9, .75)) +
  theme(legend.background = element_blank()) +
  theme(plot.margin = unit(c(.75,1,.75,.5), "cm")) ->
g
```


`r apply_reveal("visualization")`


---

# "Lateral moves"/"backstepping" to second plot - small multiples...

---

```{r small_multiples, echo = F, eval = T}
g +
  facet_wrap(~ decade) + 
  aes(col = NULL) +
  scale_x_continuous(breaks = 1:12, 
                     expand = c(0.01,0.01),
                     label = c(" jan","", "", 
                               "april", "", "", 
                               "july", "", "", 
                               "oct", "", "dec  ")) +
  labs(title = NULL) ->
gg
```

`r apply_reveal("small_multiples")`

---

# And now from the second plot back to the first...

---

```{r and_back, echo = F, eval = F}
gg +
  facet_null() + 
  aes(col = year) +
  labs(col = NULL) +
  scale_x_continuous(breaks = 1:12, 
                     expand = c(0.01,0.01),
                     label = c(" jan","feb", "march", 
                               "april", "may", "june", 
                               "july", "aug", "sept", 
                               "oct", "nov", "dec  ")) +
  labs(title = "Activity ramps up in the UN General Assembly ") 
```

`r apply_reveal("and_back")`

---





```{css, eval = TRUE, echo = F}
.remark-code{line-height: 1.5; font-size: 60%}
```


