---
title: "maps as points"
author: "Evangeline Reynolds"
date: "7/17/2019"
output: html_document
---

```{r, fig.height=20, fig.width=20}
library(tidyverse)
cinc <- readr::read_csv("../../side_projects/tidy.correlates.of.war/cinc_score/raw_data/NMC_v4_0.csv") %>% 
  mutate(country_name = 
           countrycode::countrycode(
             ccode, "cown", "country.name"
             )) %>% 
  select(country_name, year, cinc) %>% 
  drop_na() %>% 
  spread(key = year, value = cinc) %>% 
  select(`1816`, `2000`, country_name) %>% 
  drop_na()


cinc %>% 
  ggplot() +
  aes(x = `1816`) +
  aes(y = `2000`) +
  geom_point()
```

```{r}
ggplot2::map_data("world") %>% 
  mutate(country_name = 
           countrycode::countrycode(
             region, "country.name", "country.name"
             )) %>% 
  group_by(region) %>% 
  mutate(sd_max = max(c(sd(lat), sd(long)))) %>% 
  mutate(y = (lat - mean(lat))/sd_max) %>% 
  mutate(x = (long - mean(long))/sd_max ) %>% 
  right_join(ggplot2::map_data("world") %>% 
               select(region) %>% 
               distinct() %>% 
               sample_n(12)
              ) %>% 
ggplot() +
  aes(x = x, y = y, group = group) +
  geom_polygon() +
  facet_wrap(~country_name) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0)
  
```






```{r}
ggplot2::map_data("world") %>% 
  mutate(country_name = 
           countrycode::countrycode(
             region, "country.name", "country.name"
             )) %>% 
  inner_join(cinc) %>% 
  group_by(region) %>% 
  filter(subregion != "Alaska") %>% 
  mutate(sd_max = max(c(sd(lat), sd(long)))) %>% 
  mutate(y = (lat - mean(lat))/sd_max) %>% 
  mutate(x = (long - mean(long))/sd_max ) ->
prepped
prepped %>% 
  ggplot() +
  aes(group = paste(country_name,group)) +
  geom_polygon( fill = "steelblue",
                size = .01,
                col = "white") +
  aes(x = x*.03 + `1816`) +
  aes(y = y*.03 + `2000`) +
  # coord_fixed(ratio = 200) +
  theme_minimal() +
  geom_point(data = cinc,
             aes(x = `1816`,
                 y = `2000`,
                 group = NULL),
             size = 1,
             shape = 21,
             fill = "white",
             col = "grey") +
  aes(label = country_name) +
  ggrepel::geom_text_repel(force = 2, 
                           data = cinc,
             aes(x = `1816`,
                 y = `2000`,
                 group = NULL),
             size = 2) +
  geom_abline(intercept = 0, slope = 1, linetype = "dotted", color = "grey") +
  coord_equal() +
  labs(x = "Proportion of Global capabilities, 1826") +
  labs(y = "Proportion of Global capabilities, 2000")

ggsave("test.png")
```
```{r}
prepped %>%
  mutate(country_name = factor(country_name)) %>% 
  ggplot() +
  aes(y = country_name) +
  aes(`1816`) +
  geom_point(col = "grey") +
  geom_point(aes(`2000`)) +
  theme_minimal() +
  geom_polygon(data = prepped,
               aes(group = paste(country_name, group), 
                 x = x*.01 + `1816`,
                   y = y*.3 + as.numeric(factor(country_name))),
               fill = "grey"
               ) +
  geom_polygon(data = prepped,
               aes(group = paste(country_name, group), 
                 x = x*.01 + `2000`,
                   y = y*.3 + as.numeric(factor(country_name))),
               fill = "black"
               ) +
  coord_fixed(ratio = .02)

ggsave("test.png")
```

