---
title: "highcharter"
author: "Gina Reynolds, May 2019"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["kunoichi", "ninjutsu"]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r}
library(tidyverse)
library(gapminder)
library(highcharter)
```


```{r}
source("../xaringan_reveal_parenthetical.R")
```


```{r}
library(tidyverse)
library(gapminder)
data(gapminder, package = "gapminder")

gp <- gapminder %>%
  arrange(desc(year)) %>%
  distinct(country, .keep_all = TRUE)
```

```{r}
gp2 <- gapminder %>%
  select(country, year, pop) %>% 
  nest(-country) %>%
  mutate(
    data = map(data, mutate_mapping, hcaes(x = year, y = pop), drop = TRUE),
    data = map(data, list_parse)
    ) %>%
  rename(ttdata = data)



gptot <- left_join(gp, gp2, by = "country")


```


---

```{r my_hchart}
hchart(gptot, "point", hcaes(lifeExp, gdpPercap, 
        name = country, size = pop, 
        group = continent, name = country)) %>%
  hc_yAxis(type = "logarithmic") %>% 
  hc_tooltip(
    useHTML = TRUE,
    headerFormat = "<b>{point.key}</b>",
    pointFormatter = tooltip_chart(accesor = "ttdata"))
```

`r apply_reveal("my_hchart")`