---
title: "World Cup analysis"
subtitle: "Ifeoma Egbogah | made with Xaringan"
author: "<br><br>Edited by Gina Reynolds, 2019"
date: "<br>"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["kunoichi", "ninjutsu"]
    nature:
      ratio: "16:9"
      highlightLines: true
---


```{r set, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
knitr::opts_chunk$set(fig.height = 6, out.width = "100%", comment = " ", cache = T)
library(tidyverse)
source(file = "https://raw.githubusercontent.com/EvaMaeRey/little_flipbooks_library/master/xaringan_reveal_parentheses_balanced.R")
```

```{r}
url <- "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-09/squads.csv"
squads <- readr::read_csv(file = url)
```

---

```{r world_cup, eval = F, echo = F}
squads %>%
  mutate(pos = case_when(pos == "DF" ~ "Defense",
                         pos == "MF" ~ "Mid fielder",
                         pos == "GK" ~ "Goal keeper",
                         pos == "FW" ~ "Forward")) %>% 
  ggplot() +
  aes(x = caps) +
  aes(y = goals) +
  geom_point() +
  geom_smooth(method = lm) +
  aes(colour = pos) +
  scale_colour_viridis_d(option = "B", guide = F) +
  facet_wrap(~pos) +
  labs(x = "Caps") +
  labs(y = "Goals") +
  labs(title = "Relationship Between Goals and Caps") +
  labs(subtitle = "For ladies who featured in the 2019 FIFA women's world cup\nbased on players positon on the field") +
  labs(caption = "Source: data.world | Visualization: Ifeoma Egbogah") +
  theme(plot.subtitle = 
          element_text(size = 10, 
                       color = "#939184",
                       margin = 
                         margin(b = 0.1, t = -0.1,
                                l = 2, unit = "cm"),
                       face = "bold")) +
  theme(plot.caption = 
          element_text(size = 7,
                       hjust = .5,
                       margin = 
                         margin(t = 0.2,
                                b = 0,
                                unit = "cm"),
                                color = "#939184")) 
```

`r apply_reveal("world_cup")`

```{r, include = F}
save_complete_plot_from_chunk("world_cup")
```


```{css, eval = TRUE, echo = F}
.remark-code{line-height: 1.5; font-size: 65%}
```