---
title: "#TidyTuesday Highlights"
subtitle: "A flipbook made with Xaringan"
author: "<br><br>Edited by Gina Reynolds, 2019"
date: "<br>"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "ninjutsu"]
    nature:
      ratio: "16:9"
      highlightLines: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
knitr::opts_chunk$set(fig.height = 6, out.width = "100%", comment = " ", cache = T)
source("https://raw.githubusercontent.com/EvaMaeRey/little_flipbooks_library/master/xaringan_reveal_parenthetical.R")
```

```{r, child=list.files()[1]}
```



```{css, eval = TRUE, echo = F}
.remark-code{line-height: 1.5; font-size: 75%}
```

```{r xaringan-themer, include = FALSE}
library(xaringanthemer)


xaringanthemer::write_xaringan_theme(text_font_size = ".75cm",
                                     text_color = "darkblue")

xaringanthemer::mono_light(
  base_color = "#1c5253",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "200", "200i"),
  code_font_google   = google_font("Droid Mono"),
  text_font_size = ".6cm",
  code_font_size = ".2cm")
  
```
