---
title: "data from a pdf"
subtitle: ""
author: "<br><br>Gina Reynolds, October 2019"
date: "<br>"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["kunoichi", "ninjutsu"]
    nature:
      ratio: "16:9"
      highlightLines: true
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.height = 6, out.width = "100%", comment = " ", cache = T, warning = F, message = F)

source("https://raw.githubusercontent.com/EvaMaeRey/little_flipbooks_library/master/xaringan_reveal_parentheses_balanced.R")
# options(tibble.print_max = 30) 
```

Pulling Pape data from pdf appendix and cleaning it up.  This demonstrates the use of the pdftools package, string manipulation, regular expressions, and data wrangling tools. 

# Pull Pape data from pdf 

```{r, eval = T}
library(tidyverse)
library(pdftools)
pape_raw <- pdftools::pdf_text(pdf = "raw_data/pape_2003_suicide_terrorism.pdf")
```

---

# clean data

---

```{r cleaning_1, eval = T, echo = F}
library(tidyverse)
pape_raw %>% 
  # only pages 16 through 19 have data
  .[16:19] %>% 
  # combining these into scalar character string
  paste(collapse = "\n") %>% 
  # write out as text file
  write_lines(path = "data_products/temp.txt") 
```

`r apply_reveal("cleaning_1")`

---


```{r cleaning_2, eval = T, echo = F}
#read back in to parse 
# as a vector of values separated by \n
read_lines("data_products/temp.txt") %>% 
  .[46:length(text)] %>% 
  str_trim() %>% 
  str_replace_all(pattern = "\\s+", 
                  replacement = " ") %>% 
  tibble() %>% 
  rename(text = 1) %>% 
  mutate(status = 
           str_extract(text, 
                       "Complet.+|Ongoing.+")) %>% 
  fill(status) %>% 
  filter(status != text) %>% 
  mutate(status = 
           str_extract(status, 
                       "Complete|Ongoing")) %>% 
  mutate(campaign = 
           str_extract(text, 
                       "C[ao]mpaign.+|Isola.+")) %>% 
  fill(campaign) %>% 
  filter(campaign != text) %>% 
  mutate(date = str_extract(text, "[A-Z].+?\\d{4}")) %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  filter(!str_detect(text, "^Thiscontent")) %>% 
  mutate(num_killed = as.numeric(stringi::stri_reverse(str_extract(stringi::stri_reverse(text), "\\d+")))) %>% 
  mutate(weapon = str_extract(text, "[a-z]+ bombs?|bomb|grenades?|hijacked airplanes|gunmen|mines|\\w+ divers?|bus driver")) %>% 
  mutate(weapon = str_replace(weapon, "s$", "")) %>% 
  mutate(unclaimed = str_detect(text, "\\?\\?\\?")) %>% 
  mutate(num_killed_notes = str_extract(text, "\\*+")) %>% 
  mutate(num_killed_notes = 
           case_when(num_killed_notes == "*" ~ "Does not include attacker",
                     num_killed_notes == "**" ~ "Assasination target killed",
                     num_killed_notes == "***" ~ "Assassination target survived")) %>% 
  mutate(status = 
           ifelse(campaign == "IsolatedAttacks", 
                  NA, 
                  status)) %>% 
  filter(!str_detect(text, "^This")) ->
pape
```

`r apply_reveal("cleaning_2")`





```{css, eval = TRUE, echo = F}
.remark-code{line-height: 1.5; font-size: 35%}
```




