---
title: "annotation in ggplot"
subtitle: "⚔<br/>made with xaringan"
author: "Gina Reynolds"
date: "2019/01/31"
output:
  xaringan::moon_reader:
    chakra: libs/remark-latest.min.js
    lib_dir: libs
    css: ["kunoichi", "ninjutsu"]
    nature:
      ratio: "20:10"
      highlightLines: true
---



```{r, message = F, warning = F}
library(tidyverse)
library(readxl)
library(lubridate)
df_0 <- read_xlsx("raw_data/us_avg_tuition.xlsx") %>% 
  left_join(data_frame(state.abb, State = state.name))
```


```{r}
library(ggthemes)
library(ggrepel)

```

```{r}
source("../xaringan_reveal_parenthetical.R")
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.height = 6, out.width = "80%", comment = " ", cache = T, dpi = 300)
```

---

```{r tuition, eval=T, echo=F, out.width= "60%"}
set.seed(2019)
ggplot(df_0) +
  aes(x = `2004-05`) +
  aes(y = `2014-15`) +
  coord_equal() +
  labs(x = "Tuition cost in 2004, USD") +
  labs(y = "Tuition cost in 2014, USD") +
  geom_segment(aes(xend = `2004-05`, 
                   yend = `2004-05`, 
                   col = "Increase from\n2004 to 2014"), 
               alpha = .7) + 
  geom_segment(aes(xend = `2004-05`, 
                   y = 0, yend = `2004-05`, 
                   col = "2004 Tuition Cost" ), 
               alpha = .7) +
  scale_color_manual(breaks = c("Increase from\n2004 to 2014", 
                                "2004 Tuition Cost"), 
                     values = c("grey70", "grey30")) +
  aes(label = state.abb) +
  geom_point(col = "grey30") +
  ggpmisc::stat_dens2d_filter(geom = "text_repel", 
                              keep.fraction = 0.30, 
                              size = 3.8) +
  lims(x = c(0,15000)) +
  lims(y = c(0,17000)) +
  annotate(geom = "text", 
           x = 1700, y = 1700, 
           label = "Average Tuition\nCosts in 2004", 
           angle = 45, size = 2.8) +
  annotate(geom = "text", 
           x = 13300, y = 15200, 
           label = "Increase", angle = 90, size = 2.8) +
  annotate(geom = "segment", 
           x = 12900, y = 12900, 
           xend = 12900, yend = 17000, 
           arrow = arrow(length = unit(0.25, "cm")), 
           col = "darkgrey") +
  annotate(geom = "segment", 
           x = 12900, y = 12900, 
           xend = 12900, yend = 0, 
           arrow = arrow(ends = "both", 
                         length = unit(0.15, "cm"), 
                         angle = 90), 
           col = "darkgrey") +
  annotate(geom = "text", 
           x = 13300, y = 8000, 
           label = "Cost in 2004", 
           angle = 90, size = 2.8) + 
  labs(title = "Average in-state tuition fees at public 4-year: 2004 and 2014") +
  labs(subtitle = "Vis: Gina Reynolds | Data Source: onlinembapage.com") +
  labs(col = "") +
  geom_abline(slope = 1, intercept = 0, lty = 2) +
  theme_bw(base_family = "serif")
```

---

`r apply_reveal("tuition")`

---


